[package]
name = "tts"
version = "0.1.0"
authors = ["Connor Hilarides <connorcpu@live.com>"]

[dependencies.winapi]
path = "../winapi-rs"
version = "*"

[dependencies.ole32-sys]
path = "../winapi-rs/lib/ole32-sys"
version = "*"
